on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created, edited]
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Please use Japanese."
          PR_AGENT.EXTRA_INSTRUCTIONS: "Please use Japanese."
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "Please use Japanese."
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "true"
          CONFIG.MODEL: "gpt-4o-mini"
          CONFIG.MODEL_TURBO: "gpt-4o-mini"
          CONFIG.FALLBACK_MODELS: "[\"gpt-4o-mini\"]"
